name: mustache_recase
description: A mustache extension for handling case conversions
version: 0.0.1
homepage: https://github.com/Rodsevich/mustache_recase/
author: Rodsevich <nicorodsevich@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  mustache: ^0.2.5
  recase: ^1.0.0

dev_dependencies:
  test: ^0.12.0
  generator_plus:
    git: https://github.com/Rodsevich/generator-plus/
